name: Release Widget

on:
  push:
    branches:
      - widget # Or your primary branch name

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create Release PR or Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags for changesets
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use an appropriate LTS version
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # Use 'ci' for faster, more reliable installs in CI environments

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This command publishes if a new version exists in the commit history (e.g., after merging the version PR).
          # If changesets are present but no version bump, it runs 'changeset version', commits the changes (version bumps, changelogs),
          # pushes to a new branch, and creates a PR titled with the 'title' input.
          publish: npm run publish:widget:ci # Assumes 'publish:widget:ci' script exists in root package.json
          commit: "chore: update package versions and changelogs"
          title: "chore: update package versions and changelogs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Your NPM authentication token secret
          # Consider enabling NPM provenance for enhanced supply-chain security
          # Requires Node >=18.17.0 and npm >=9.7.0
          # NPM_CONFIG_PROVENANCE: "true"
